version: '3'

vars:
  GIT_COMMIT:
    sh: git rev-parse HEAD

  VERSION:
    sh: git describe --tags {{.GIT_COMMIT}} 2> /dev/null || echo "{{.GIT_COMMIT}}"

tasks:
  build:
    desc: Builds the CLI
    cmds:
      - mkdir -p bin
      - go build -ldflags="github.com/yukitsune/amjwt.Version={{.VERSION}}" -o ./bin/ ./cmd/...

  test:
    desc: Runs all tests
    cmds:
      - go test -v ./...

  clean:
    desc: Removes the bin directory
    cmds:
      - rm -rf bin
